default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: tiae_development

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB', 'tiae_test') %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  username: <%= ENV.fetch('POSTGRES_USER', nil) %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', nil) %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>

production:
  <<: *default
  database: tiae
